In [5]:
'''
This part of the code comment is similar to the fusion model, refer to the fusion model file
'''
import pandas as pd
import numpy as np
import joblib
from sklearn.utils import shuffle


In [6]:
HC_SP = joblib.load(r"E:\DIY_feature\vaild_data\HC_SP\HC_SP.pkl")
SP_BP = joblib.load(r'E:\DIY_feature\vaild_data\SP_BP\SP_BP.pkl') 

In [7]:
Vaild_features = pd.read_excel(r"C:\Users\Yunheng\Desktop\paper\data\new\Healthy Control, Schizophrenia and Bipolar Disorder\vaild_data.xlsx")
HC_SP_test_features = pd.read_csv(r"C:\Users\Yunheng\Desktop\paper\data\new\Healthy Control and Schizophrenia\Healthy Control and Schizophrenia train features.csv")
SP_BP_test_features = pd.read_csv(r"C:\Users\Yunheng\Desktop\paper\data\new\Schizophrenia and Bipolar Disorder\Schizophrenia and Bipolar Disorder train features.csv")


In [8]:
targets = pd.DataFrame(Vaild_features['disease'])

In [9]:
HC_SP_test = pd.DataFrame()
HC_SP_feature_index = HC_SP_test_features.drop(columns=["disease"]).columns
for i in range(len(HC_SP_feature_index)):
    HC_SP_test["%s"%HC_SP_feature_index[i]] = vaild_features['%s'%HC_SP_feature_index[i]].values

In [10]:
HC_SP_Pre = HC_SP.predict(HC_SP_test)
print( np.array(targets).reshape((-1,)))
print(HC_SP_Pre)

[0 0 1 0 1 3 3 1 3 0 1 0 1 1 3 1 0 0 3 1 3]
[1 0 1 0 1 1 1 1 1 0 1 0 1 1 0 1 0 0 1 1 1]


In [11]:
healthy_index = []
for i in range(len(HC_SP_Pre)):
    if HC_SP_Pre[i] == 0:
        healthy_index.append(i)

In [12]:
vaild_features = vaild_features.drop(vaild_features.index[healthy_index])

In [13]:
SP_BP_test = pd.DataFrame()
SP_BP_feature_index = SP_BP_test_features.drop(columns=["disease"]).columns
for i in range(len(SP_BP_feature_index)):
    SP_BP_test["%s"%SP_BP_feature_index[i]] = vaild_features['%s'%SP_BP_feature_index[i]].values

In [14]:
SP_BP_targets = pd.DataFrame(vaild_features['disease'])

In [15]:
SP_BP_Pre = SP_BP.predict(SP_BP_test)
print( np.array(SP_BP_targets).reshape((-1,)))
print(SP_BP_Pre)

[0 1 1 3 3 1 3 1 1 1 1 3 1 3]
[1 1 1 3 1 1 3 1 1 1 1 3 3 3]
